config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get 'users/create'

  get 'users/show'

  root "pages#index"

  # users routes
  # get "/signup", to: "users#new"
  # get "/profile", to: "users#show"

  # sessions routes
  # get "/login", to: "sessions#new"
  # get "/logout", to: "sessions#destroy"
  # resources :sessions, only: [:create]

  # blog post routes
  resources :posts

  resources :users, only: [:new, :create, :show]

end

#    Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         pages#index
#     posts GET    /posts(.:format)          posts#index
#           POST   /posts(.:format)          posts#create
#  new_post GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
#      post GET    /posts/:id(.:format)      posts#show
#           PATCH  /posts/:id(.:format)      posts#update
#           PUT    /posts/:id(.:format)      posts#update
#           DELETE /posts/:id(.:format)      posts#destroy
#     users POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
#      user GET    /users/:id(.:format)      users#show
#      DELETE /posts/:id(.:format)      posts#destroy

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
		render :index
	end

	def show
		# set id from URL params
		post_id = params[:id]

		# find plane in db by id
		@post = Post.find(post_id)

		#render show view
		render :show
	end

	def new
		@post = Post.new
		render :new
	end

	def create
		post_params = params.require(:post).permit(:title, :body)
		Post.create(post_params)
		redirect_to posts_path 
	end

	def edit
		# set id from params
		post_id = params[:id]

		# find post in db by its id
		@post = Post.find(post_id)

		# render edit view
		render :edit
	end

	def update
		# set id from params
		post_id = params[:id]

		# find post in db by its id
		@post = Post.find(post_id)

		# updated post data from forms
		post_params = params.require(:post).permit(:title, :body)

		# update the post in db
		@post.update_attributes(post_params)

		# render edit view
		render :show
	end

	def destroy
		# set id from params
		post_id = params[:id]

		# find the plane by its id
		post = Post.find(post_id)

		# delete it from the db
		post.destroy

		redirect_to posts_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  	render :new
  end

  def create
  	user = User.create(user_params)
    session[:user_id] = user.id

    # redirect_to "/users/#{user.id}"
    # the line above can be refactored to use rails route helpers:
    redirect_to user_path(user)
  end

  def show
    @user = User.find(session[:user_id])
    render :show
  end

  private
      def user_params
        params.require(:user).permit(:email, :password)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/page/index.html.erb</p>


<%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<hr>
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "title", class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "body", class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<%= link_to "Delete", post_path(@post.id), method: :delete %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<%= link_to "New Post", new_post_path %>
<br>
<br>
<% @posts.each do |post| %>

    <div>
        Name: <%= post.title %> <br>
        Type: <%= post.body %> <br>
        <%= link_to "Edit Post", edit_post_path(id: post.id) %>
    </div>
    <br>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<hr>
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "title", class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "body", class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<h3>Post</h3>
<br>
<div>
	<strong>Title: </strong><%= @post.title %><br>
	<strong>Body: </strong><%= @post.body %><br>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<%= form_for @user do |f| %>
  <%= f.email_field :email, placeholder: "Email", autofocus: true %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

<br>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

Welcome, <%= @user.email %>!